#!/usr/bin/env bash
# Server lb-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add ~/.sshlb-01/school

# Username and IP Address 
ssh ubuntu@34.234.193.72

