#!/usr/bin/env bash
# Server-02 login commands

# Setting up the SSH-agent
eval $("ssh-agent")

# Path to IdentityFile
ssh-add ~/.sshweb-02/school

# Username and IP Address 
ssh ubuntu@100.26.243.112
