#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*
sudo chown -R "$USER":"$USER" /etc/default/
sudo chown -R "$USER":"$USER" /etc/haproxy/

# edit config file
server_config=\
"
defaults
    mode http
    timeout client  50000s
    timeout connect 5000s
    timeout server  50000s
    timeout http-request 5000s

frontend  safiya-tech_frontend
        bind *:443
        default_backend safiya-tech_backend

backend safiya-tech_backend
        balance roundrobin
        server 419745-web-01 34.224.2.217:443 check
        server 419745-web-02 100.26.243.112:443 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart


