#!/usr/bin/env bash
# SSH client configuration 

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes 
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    RSAAuthentication yes
    PubkeyAuthentication yes
    AuthorizedKeysFile .ssh/authorized_keys
